/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.learner.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DataFields extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DataFields\",\"namespace\":\"org.librairy.service.learner.facade.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"labels\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]},{\"name\":\"text\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.String id;
   private java.util.List<java.lang.String> labels;
   private java.util.List<java.lang.String> text;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public DataFields() {}

  /**
   * All-args constructor.
   */
  public DataFields(java.lang.String id, java.util.List<java.lang.String> labels, java.util.List<java.lang.String> text) {
    this.id = id;
    this.labels = labels;
    this.text = text;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return labels;
    case 2: return text;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: labels = (java.util.List<java.lang.String>)value$; break;
    case 2: text = (java.util.List<java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'labels' field.
   */
  public java.util.List<java.lang.String> getLabels() {
    return labels;
  }

  /**
   * Sets the value of the 'labels' field.
   * @param value the value to set.
   */
  public void setLabels(java.util.List<java.lang.String> value) {
    this.labels = value;
  }

  /**
   * Gets the value of the 'text' field.
   */
  public java.util.List<java.lang.String> getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.util.List<java.lang.String> value) {
    this.text = value;
  }

  /** Creates a new DataFields RecordBuilder */
  public static org.librairy.service.learner.facade.model.DataFields.Builder newBuilder() {
    return new org.librairy.service.learner.facade.model.DataFields.Builder();
  }
  
  /** Creates a new DataFields RecordBuilder by copying an existing Builder */
  public static org.librairy.service.learner.facade.model.DataFields.Builder newBuilder(org.librairy.service.learner.facade.model.DataFields.Builder other) {
    return new org.librairy.service.learner.facade.model.DataFields.Builder(other);
  }
  
  /** Creates a new DataFields RecordBuilder by copying an existing DataFields instance */
  public static org.librairy.service.learner.facade.model.DataFields.Builder newBuilder(org.librairy.service.learner.facade.model.DataFields other) {
    return new org.librairy.service.learner.facade.model.DataFields.Builder(other);
  }
  
  /**
   * RecordBuilder for DataFields instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataFields>
    implements org.apache.avro.data.RecordBuilder<DataFields> {

    private java.lang.String id;
    private java.util.List<java.lang.String> labels;
    private java.util.List<java.lang.String> text;

    /** Creates a new Builder */
    private Builder() {
      super(org.librairy.service.learner.facade.model.DataFields.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.librairy.service.learner.facade.model.DataFields.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.labels)) {
        this.labels = data().deepCopy(fields()[1].schema(), other.labels);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.text)) {
        this.text = data().deepCopy(fields()[2].schema(), other.text);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DataFields instance */
    private Builder(org.librairy.service.learner.facade.model.DataFields other) {
            super(org.librairy.service.learner.facade.model.DataFields.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.labels)) {
        this.labels = data().deepCopy(fields()[1].schema(), other.labels);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.text)) {
        this.text = data().deepCopy(fields()[2].schema(), other.text);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.String getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.librairy.service.learner.facade.model.DataFields.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.librairy.service.learner.facade.model.DataFields.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'labels' field */
    public java.util.List<java.lang.String> getLabels() {
      return labels;
    }
    
    /** Sets the value of the 'labels' field */
    public org.librairy.service.learner.facade.model.DataFields.Builder setLabels(java.util.List<java.lang.String> value) {
      validate(fields()[1], value);
      this.labels = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'labels' field has been set */
    public boolean hasLabels() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'labels' field */
    public org.librairy.service.learner.facade.model.DataFields.Builder clearLabels() {
      labels = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'text' field */
    public java.util.List<java.lang.String> getText() {
      return text;
    }
    
    /** Sets the value of the 'text' field */
    public org.librairy.service.learner.facade.model.DataFields.Builder setText(java.util.List<java.lang.String> value) {
      validate(fields()[2], value);
      this.text = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'text' field has been set */
    public boolean hasText() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'text' field */
    public org.librairy.service.learner.facade.model.DataFields.Builder clearText() {
      text = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public DataFields build() {
      try {
        DataFields record = new DataFields();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.labels = fieldSetFlags()[1] ? this.labels : (java.util.List<java.lang.String>) defaultValue(fields()[1]);
        record.text = fieldSetFlags()[2] ? this.text : (java.util.List<java.lang.String>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
