/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.learner.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Format { 
  SOLR_CORE, CSV, CSV_TAR_GZ, JSONL, JSONL_TAR_GZ  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Format\",\"namespace\":\"org.librairy.service.learner.facade.model\",\"symbols\":[\"SOLR_CORE\",\"CSV\",\"CSV_TAR_GZ\",\"JSONL\",\"JSONL_TAR_GZ\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
