/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.learner.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Language { 
  EN, ES, FR, DE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Language\",\"namespace\":\"org.librairy.service.learner.facade.model\",\"symbols\":[\"EN\",\"ES\",\"FR\",\"DE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
