/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.learner.facade.model;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface LearnerService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"LearnerService\",\"namespace\":\"org.librairy.service.learner.facade.model\",\"types\":[{\"type\":\"record\",\"name\":\"DataFields\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"labels\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]},{\"name\":\"text\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]}]},{\"type\":\"record\",\"name\":\"DataSource\",\"fields\":[{\"name\":\"url\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"format\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"filter\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"size\",\"type\":\"long\"},{\"name\":\"fields\",\"type\":\"DataFields\"}]},{\"type\":\"record\",\"name\":\"TopicsRequest\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"created by librAIry\"},{\"name\":\"version\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"1.0\"},{\"name\":\"contactEmail\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"parameters\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},\"default\":{}},{\"name\":\"from\",\"type\":\"DataSource\"}]}],\"messages\":{\"createTopics\":{\"request\":[{\"name\":\"request\",\"type\":\"TopicsRequest\"}],\"response\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"cleanCache\":{\"request\":[],\"response\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}}");
  java.lang.String createTopics(org.librairy.service.learner.facade.model.TopicsRequest request) throws org.apache.avro.AvroRemoteException;
  java.lang.String cleanCache() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends LearnerService {
    public static final org.apache.avro.Protocol PROTOCOL = org.librairy.service.learner.facade.model.LearnerService.PROTOCOL;
    void createTopics(org.librairy.service.learner.facade.model.TopicsRequest request, org.apache.avro.ipc.Callback<java.lang.String> callback) throws java.io.IOException;
    void cleanCache(org.apache.avro.ipc.Callback<java.lang.String> callback) throws java.io.IOException;
  }
}