/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.learner.facade.model;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface LearnerService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"LearnerService\",\"namespace\":\"org.librairy.service.learner.facade.model\",\"types\":[{\"type\":\"enum\",\"name\":\"Language\",\"symbols\":[\"EN\",\"ES\",\"FR\",\"DE\"]},{\"type\":\"record\",\"name\":\"Corpus\",\"fields\":[{\"name\":\"path\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"language\",\"type\":\"Language\"},{\"name\":\"separator\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\";\"},{\"name\":\"idIndex\",\"type\":\"int\",\"default\":-1},{\"name\":\"textIndex\",\"type\":\"int\",\"default\":0}]},{\"type\":\"record\",\"name\":\"Hyperparameters\",\"fields\":[{\"name\":\"alpha\",\"type\":\"double\",\"default\":0.1},{\"name\":\"beta\",\"type\":\"double\",\"default\":0.001},{\"name\":\"topics\",\"type\":\"int\",\"default\":5},{\"name\":\"wordsPerTopic\",\"type\":\"int\",\"default\":20},{\"name\":\"iterations\",\"type\":\"int\",\"default\":1000}]}],\"messages\":{\"train\":{\"request\":[{\"name\":\"corpus\",\"type\":\"Corpus\"},{\"name\":\"parameters\",\"type\":\"Hyperparameters\"},{\"name\":\"extra\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},\"default\":{}}],\"response\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"inference\":{\"request\":[{\"name\":\"corpus\",\"type\":\"Corpus\"},{\"name\":\"model\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"response\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}}");
  java.lang.String train(org.librairy.service.learner.facade.model.Corpus corpus, org.librairy.service.learner.facade.model.Hyperparameters parameters, java.util.Map<java.lang.String,java.lang.String> extra) throws org.apache.avro.AvroRemoteException;
  java.lang.String inference(org.librairy.service.learner.facade.model.Corpus corpus, java.lang.String model) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends LearnerService {
    public static final org.apache.avro.Protocol PROTOCOL = org.librairy.service.learner.facade.model.LearnerService.PROTOCOL;
    void train(org.librairy.service.learner.facade.model.Corpus corpus, org.librairy.service.learner.facade.model.Hyperparameters parameters, java.util.Map<java.lang.String,java.lang.String> extra, org.apache.avro.ipc.Callback<java.lang.String> callback) throws java.io.IOException;
    void inference(org.librairy.service.learner.facade.model.Corpus corpus, java.lang.String model, org.apache.avro.ipc.Callback<java.lang.String> callback) throws java.io.IOException;
  }
}