/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.learner.facade.model;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface LearnerService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"LearnerService\",\"namespace\":\"org.librairy.service.learner.facade.model\",\"types\":[],\"messages\":{\"train\":{\"request\":[{\"name\":\"corpus\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"parameters\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},\"default\":{}},{\"name\":\"mapping\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},\"default\":{}}],\"response\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}}");
  java.lang.String train(java.lang.String corpus, java.util.Map<java.lang.String,java.lang.String> parameters, java.util.Map<java.lang.String,java.lang.String> mapping) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends LearnerService {
    public static final org.apache.avro.Protocol PROTOCOL = org.librairy.service.learner.facade.model.LearnerService.PROTOCOL;
    void train(java.lang.String corpus, java.util.Map<java.lang.String,java.lang.String> parameters, java.util.Map<java.lang.String,java.lang.String> mapping, org.apache.avro.ipc.Callback<java.lang.String> callback) throws java.io.IOException;
  }
}